### ISSUE TITLE
Remove Seattle Files from base folders

### ISSUE THREAD

**Issue by Dickmcmanus** [manbe003/policing#26]
Currently, there is a dirty data/seattle and clean data/seattle directory but our base directory folder still has the following files:

Call_Data_Seattle.csv
Officer_involved_shooting_Seattle.csv
citations_seattle.csv
data cleaning script_Seattle.R
functions file.R
script for comparing variables.R
use_of_force_Seattle.csv

These all appear to have copies now in the appropriate sub folder. Please confirm the subfolder files are the most current versions and that these base folder files can be removed, and do so.

**Comment by Dickmcmanus** [comment]
This also seems to be true in the sub folders Dirty Data and Clean Data, they each have several files that likely are duplicates from the Seattle Sub folder.

**Comment by manbe003** [comment]
I tried to do this! It worked on github but now when I try to pull there is an error (error: invalid path 'clean data/orlando/script for UOF:shootings comparing.R'
Updating 91d7581..205c1bb)

I have looked around a bit to try to troubleshoot but feel pretty frustrated. Wondering if this might be some good modeling to bring to you at our code troubleshoot meeting tomorrow?

**Comment by Dickmcmanus** [comment]
@manbe003 accept my PRs, and then try to pull to your master, and see if that works.
