### ISSUE TITLE
Add Team as collaborators

### ISSUE THREAD

**Issue by Dickmcmanus** [manbe003/policing#28]
Right now the team are Contributors, meaning they must submit PRs from their cloned repos. However, we can give them direct access as Collaborators, so they can create direct branches on this repo, which will reduce the work needed to submit PRs and allow me to copy their branches onto my computer and work through problems with them.

Please when in the manbe003/policing repo, go to Settings -> Manage Access -> Invite collaborators to add the team members.

**Comment by manbe003** [comment]
Katie and Kranshasi have been added but I need to figure out Arya and Alexis usernames.
